// <auto-generated />
using System;
using BlogPlatform.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogPlatform.Migrations
{
    [DbContext(typeof(BlogPlatformContext))]
    [Migration("20200629125019_ChangeSeedData")]
    partial class ChangeSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogPlatform.Models.Content", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContentId");

                    b.HasIndex("GenreId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            ContentId = 1,
                            Author = "Jay Bowen",
                            Body = "Or forefather produced furniture at an incredible rate.  Is this because they were just that much more talented than we are today?  Possibly but they had the benefit of not knowing any other way to work and they took advantage of the unique nature of hand work to be efficient and eliminate steps that we would go through today in order to work with a machine.  ",
                            GenreId = 1,
                            PublishDate = new DateTime(2020, 6, 29, 8, 50, 18, 588, DateTimeKind.Local).AddTicks(6968),
                            Title = "Taking the Tool to Wood"
                        },
                        new
                        {
                            ContentId = 2,
                            Author = "Ron Wynn",
                            Body = "Nails not only are 'acceptable' in your woodworking projects but they have experienced a resurgence in popularity.  But these are not the wire nails you will find at the typical hardware store.  These are the 18th and 19th century variants: cut nails and wrought nails.  Both of these types of nails have substantially more holding power then the modern equivalents but require a bit more care when driving them in.  First and foremost, in almost all cases you will want to bore a pilot hole before you reach for the hammer.",
                            GenreId = 1,
                            PublishDate = new DateTime(2020, 6, 29, 8, 50, 18, 591, DateTimeKind.Local).AddTicks(4398),
                            Title = "Nails 101"
                        },
                        new
                        {
                            ContentId = 3,
                            Author = "Ron Wynn",
                            Body = "In its simplest form, a kitchen garden produces fresh fruits, vegetables and herbs for delicious, healthy meals. A kitchen garden doesn’t have to be right outside the kitchen door, but the closer it is, the better. Think about it this way: The easier it is for you to get into the garden, the more likely it is that you will get tasty things out of it. Did you forget to add the chopped dill on your boiled red-skinned potatoes? No problem — it’s just steps away.",
                            GenreId = 2,
                            PublishDate = new DateTime(2020, 6, 29, 8, 50, 18, 591, DateTimeKind.Local).AddTicks(4501),
                            Title = "Grow your own food"
                        },
                        new
                        {
                            ContentId = 4,
                            Author = "Jay Bowen",
                            Body = "Your pool and spa are big investments, so it’s important to maintain them year-round. In this blog, we’ll go over the winterization basics for inground pools and above ground pools, as well as touch on spas and recommended products.",
                            GenreId = 3,
                            PublishDate = new DateTime(2020, 6, 29, 8, 50, 18, 591, DateTimeKind.Local).AddTicks(4509),
                            Title = "Winterize your pool"
                        });
                });

            modelBuilder.Entity("BlogPlatform.Models.ContentTag", b =>
                {
                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ContentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ContentTag");

                    b.HasData(
                        new
                        {
                            ContentId = 1,
                            TagId = 1
                        },
                        new
                        {
                            ContentId = 1,
                            TagId = 2
                        },
                        new
                        {
                            ContentId = 2,
                            TagId = 1
                        },
                        new
                        {
                            ContentId = 2,
                            TagId = 3
                        },
                        new
                        {
                            ContentId = 3,
                            TagId = 2
                        },
                        new
                        {
                            ContentId = 3,
                            TagId = 3
                        });
                });

            modelBuilder.Entity("BlogPlatform.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Build furniture today!",
                            ImageName = "Wood.jpg",
                            Name = "Woodworking"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Growing Extremely Hot Peppers",
                            ImageName = "Garden.jpg",
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Backyard adventures await",
                            ImageName = "Pools.jpg",
                            Name = "Pools"
                        });
                });

            modelBuilder.Entity("BlogPlatform.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hot Peppers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mild Peppers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Corn"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rafting"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Oak"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Maple"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Table Saw"
                        });
                });

            modelBuilder.Entity("BlogPlatform.Models.Content", b =>
                {
                    b.HasOne("BlogPlatform.Models.Genre", "Genre")
                        .WithMany("Content")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogPlatform.Models.ContentTag", b =>
                {
                    b.HasOne("BlogPlatform.Models.Content", "Content")
                        .WithMany("ContentTags")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPlatform.Models.Tag", "Tag")
                        .WithMany("ContentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
